name: "Podcast Generator"
author: "Chanikya Boggarapu"
description: "Generates feed for Lin-Project from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email: 
    description: The commiter's email address
    required: True
    default: ${{ github.actor }}@localhost
  name:
    description: This is commiter's name
    required: True
    default: ${{ github.actor }}